/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Color;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.border.Border;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author W1710551 - Christopher Rees
 */
public final class Dashboard extends javax.swing.JFrame {

    static boolean maximized = true;
    static boolean loggedIn = true;
    int xMouse;
    int yMouse;
    
    public Dashboard() {
        initComponents();
        getProjectTable();
        findProject(searchResults, searchInput);
        // Create border for DashboardContainer to Black
        Border container_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        dashboardContainer.setBorder(container_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        minimizeBtn = new javax.swing.JButton();
        navBar = new javax.swing.JPanel();
        profileBtn = new javax.swing.JButton();
        chartsBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        dashboardContainer = new javax.swing.JPanel();
        profileTab = new javax.swing.JScrollPane();
        profileContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userfNameTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        userType = new javax.swing.JLabel();
        sessionID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        userfName = new javax.swing.JLabel();
        userlName = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lastLogin = new javax.swing.JLabel();
        lineSeperator = new javax.swing.JLabel();
        lineSeperator1 = new javax.swing.JLabel();
        adminControlPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addData = new javax.swing.JButton();
        userLog = new javax.swing.JButton();
        chartsTab = new javax.swing.JPanel();
        chartsLbl = new javax.swing.JLabel();
        cwInfoPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cwContainer = new javax.swing.JPanel();
        chartDataSelect = new javax.swing.JPanel();
        chartPreview = new javax.swing.JButton();
        proChartSelect = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        searchTab = new javax.swing.JPanel();
        searchLbl = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResults = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        logoutTab = new javax.swing.JPanel();
        logoutLbl = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        logoutWarningLbl = new javax.swing.JLabel();
        confirmLogoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("dashboard");
        setName("dashboard"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        titleBar.setBackground(new java.awt.Color(0, 0, 0));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(0, 0, 0));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/exit.png"))); // NOI18N
        exitBtn.setToolTipText("Exit");
        exitBtn.setContentAreaFilled(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn.setMaximumSize(new java.awt.Dimension(64, 64));
        exitBtn.setMinimumSize(new java.awt.Dimension(64, 64));
        exitBtn.setOpaque(true);
        exitBtn.setPreferredSize(new java.awt.Dimension(64, 64));
        exitBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/exitSelected.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
        });
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        minimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/minimize.png"))); // NOI18N
        minimizeBtn.setToolTipText("Minimize");
        minimizeBtn.setContentAreaFilled(false);
        minimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        minimizeBtn.setMaximumSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setMinimumSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setOpaque(true);
        minimizeBtn.setPreferredSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/minimizeSelected.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        navBar.setBackground(new java.awt.Color(0, 0, 0));

        profileBtn.setBackground(new java.awt.Color(0, 0, 0));
        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/user.png"))); // NOI18N
        profileBtn.setToolTipText("Profile");
        profileBtn.setContentAreaFilled(false);
        profileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBtn.setOpaque(true);
        profileBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/userSelected.png"))); // NOI18N
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        chartsBtn.setBackground(new java.awt.Color(0, 0, 0));
        chartsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/charts.png"))); // NOI18N
        chartsBtn.setToolTipText("Charts");
        chartsBtn.setContentAreaFilled(false);
        chartsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chartsBtn.setFocusTraversalPolicyProvider(true);
        chartsBtn.setOpaque(true);
        chartsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/chartsSelected.png"))); // NOI18N
        chartsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartsBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/search.png"))); // NOI18N
        searchBtn.setToolTipText("Search");
        searchBtn.setContentAreaFilled(false);
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.setOpaque(true);
        searchBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/searchSelected.png"))); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(0, 0, 0));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/logout.png"))); // NOI18N
        logoutBtn.setToolTipText("Logout");
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setOpaque(true);
        logoutBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/logoutSelected.png"))); // NOI18N
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
        navBar.setLayout(navBarLayout);
        navBarLayout.setHorizontalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(chartsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        navBarLayout.setVerticalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(chartsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        dashboardContainer.setLayout(new java.awt.CardLayout());

        profileTab.setBackground(new java.awt.Color(255, 255, 255));
        profileTab.setBorder(null);
        profileTab.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        profileContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Welcome back,");

        userfNameTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        userfNameTitle.setForeground(new java.awt.Color(255, 51, 51));
        userfNameTitle.setText("Chris");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setText("User Type:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Session ID: ");

        userName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 51, 51));
        userName.setText("chrisrees");

        userType.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        userType.setForeground(new java.awt.Color(255, 51, 51));
        userType.setText("Administrator");

        sessionID.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        sessionID.setForeground(new java.awt.Color(255, 51, 51));
        sessionID.setText("792034");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("First Name:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Last Name:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Email:");

        userfName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        userfName.setForeground(new java.awt.Color(255, 51, 51));
        userfName.setText("Christopher");

        userlName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        userlName.setForeground(new java.awt.Color(255, 51, 51));
        userlName.setText("Rees");

        userEmail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        userEmail.setForeground(new java.awt.Color(255, 51, 51));
        userEmail.setText("chris@xnolabs.com");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setText("Last Login: ");

        lastLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lastLogin.setForeground(new java.awt.Color(255, 51, 51));
        lastLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lastLogin.setText("16/03/2020 20:08");

        lineSeperator.setBackground(new java.awt.Color(0, 0, 0));
        lineSeperator.setToolTipText("");
        lineSeperator.setOpaque(true);

        lineSeperator1.setBackground(new java.awt.Color(0, 0, 0));
        lineSeperator1.setToolTipText("");
        lineSeperator1.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Admin Control Panel");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        addData.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        addData.setText("Add New Data Wizard");
        addData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataActionPerformed(evt);
            }
        });

        userLog.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        userLog.setText("User Log");
        userLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminControlPanelLayout = new javax.swing.GroupLayout(adminControlPanel);
        adminControlPanel.setLayout(adminControlPanelLayout);
        adminControlPanelLayout.setHorizontalGroup(
            adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(adminControlPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLog, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        adminControlPanelLayout.setVerticalGroup(
            adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLog)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout profileContainerLayout = new javax.swing.GroupLayout(profileContainer);
        profileContainer.setLayout(profileContainerLayout);
        profileContainerLayout.setHorizontalGroup(
            profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileContainerLayout.createSequentialGroup()
                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineSeperator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(profileContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileContainerLayout.createSequentialGroup()
                        .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sessionID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(profileContainerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(userfNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(profileContainerLayout.createSequentialGroup()
                        .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profileContainerLayout.createSequentialGroup()
                                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userlName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userfName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(adminControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        profileContainerLayout.setVerticalGroup(
            profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userfNameTitle)
                    .addComponent(jLabel16)
                    .addComponent(lastLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sessionID))
                .addGap(18, 18, 18)
                .addComponent(lineSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userfName)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(userlName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(userEmail))
                .addGap(81, 81, 81)
                .addComponent(lineSeperator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        profileTab.setViewportView(profileContainer);

        dashboardContainer.add(profileTab, "card2");

        chartsTab.setBackground(new java.awt.Color(255, 255, 255));

        chartsLbl.setBackground(new java.awt.Color(255, 255, 255));
        chartsLbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        chartsLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chartsLbl.setText("CHART WIZARD");
        chartsLbl.setOpaque(true);

        cwInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        cwInfoPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel11.setText("How to use:");

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel17.setText("1. Select Chart Type & Data Type & Click Continue");

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel20.setText("2. Select XY Axis & Click Preview Chart");

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel21.setText("3. Select Save to add to your Profile Dashboard or Delete/Exit to start again");

        javax.swing.GroupLayout cwInfoPanelLayout = new javax.swing.GroupLayout(cwInfoPanel);
        cwInfoPanel.setLayout(cwInfoPanelLayout);
        cwInfoPanelLayout.setHorizontalGroup(
            cwInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cwInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cwInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cwInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cwInfoPanelLayout.setVerticalGroup(
            cwInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cwInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cwContainer.setBackground(new java.awt.Color(255, 255, 255));
        cwContainer.setLayout(new java.awt.CardLayout());

        chartPreview.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        chartPreview.setText("Preview");
        chartPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartPreviewActionPerformed(evt);
            }
        });

        proChartSelect.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        proChartSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Project Status vs Total Cost", "Co-Ordinator Country vs Project Status", "Total Signed Projects", "Signed Grants/Participant EU Contribution" }));
        proChartSelect.setToolTipText("");

        jLabel25.setText("Choose available Chart:");

        javax.swing.GroupLayout chartDataSelectLayout = new javax.swing.GroupLayout(chartDataSelect);
        chartDataSelect.setLayout(chartDataSelectLayout);
        chartDataSelectLayout.setHorizontalGroup(
            chartDataSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartDataSelectLayout.createSequentialGroup()
                .addGroup(chartDataSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chartDataSelectLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(chartDataSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(proChartSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(chartDataSelectLayout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(chartPreview)))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        chartDataSelectLayout.setVerticalGroup(
            chartDataSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartDataSelectLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proChartSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(chartPreview)
                .addGap(33, 33, 33))
        );

        cwContainer.add(chartDataSelect, "card3");

        javax.swing.GroupLayout chartsTabLayout = new javax.swing.GroupLayout(chartsTab);
        chartsTab.setLayout(chartsTabLayout);
        chartsTabLayout.setHorizontalGroup(
            chartsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cwContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cwInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chartsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chartsTabLayout.setVerticalGroup(
            chartsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartsTabLayout.createSequentialGroup()
                .addComponent(chartsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cwInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cwContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dashboardContainer.add(chartsTab, "card5");

        searchTab.setBackground(new java.awt.Color(255, 255, 255));

        searchLbl.setBackground(new java.awt.Color(255, 255, 255));
        searchLbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        searchLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchLbl.setText("SEARCH");
        searchLbl.setOpaque(true);

        searchResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(searchResults);

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Search Project:");

        javax.swing.GroupLayout searchTabLayout = new javax.swing.GroupLayout(searchTab);
        searchTab.setLayout(searchTabLayout);
        searchTabLayout.setHorizontalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchTabLayout.createSequentialGroup()
                        .addComponent(searchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(searchTabLayout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchInput))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE))
                .addContainerGap())
        );
        searchTabLayout.setVerticalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboardContainer.add(searchTab, "card6");

        logoutTab.setBackground(new java.awt.Color(255, 255, 255));

        logoutLbl.setBackground(new java.awt.Color(255, 255, 255));
        logoutLbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        logoutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLbl.setText("LOGOUT");
        logoutLbl.setOpaque(true);

        logoutIcon.setBackground(new java.awt.Color(255, 255, 255));
        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/logoutIcon.png"))); // NOI18N
        logoutIcon.setToolTipText("");
        logoutIcon.setOpaque(true);

        logoutWarningLbl.setBackground(new java.awt.Color(255, 255, 255));
        logoutWarningLbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        logoutWarningLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutWarningLbl.setText("Are you sure?");
        logoutWarningLbl.setOpaque(true);

        confirmLogoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        confirmLogoutBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        confirmLogoutBtn.setText("LOGOUT");
        confirmLogoutBtn.setBorder(null);
        confirmLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmLogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoutTabLayout = new javax.swing.GroupLayout(logoutTab);
        logoutTab.setLayout(logoutTabLayout);
        logoutTabLayout.setHorizontalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutTabLayout.createSequentialGroup()
                .addContainerGap(513, Short.MAX_VALUE)
                .addGroup(logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutWarningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(406, 406, 406))
        );
        logoutTabLayout.setVerticalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(logoutIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutWarningLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        dashboardContainer.add(logoutTab, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dashboardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1096, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        if(maximized) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_titleBarMouseDragged

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        profileBtn.setBackground(new Color(255, 255, 255));
        
        chartsBtn.setBackground(new Color(0, 0, 0));
        searchBtn.setBackground(new Color(0, 0, 0));
        logoutBtn.setBackground(new Color(0, 0, 0));
        
        dashboardContainer.removeAll();
        dashboardContainer.repaint();
        dashboardContainer.revalidate();
        dashboardContainer.add(profileTab);
        dashboardContainer.repaint();
        dashboardContainer.revalidate();
    }//GEN-LAST:event_profileBtnActionPerformed

    private void chartsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartsBtnActionPerformed
        chartsBtn.setBackground(new Color(255, 255, 255));
        
        profileBtn.setBackground(new Color(0, 0, 0));
        searchBtn.setBackground(new Color(0, 0, 0));
        logoutBtn.setBackground(new Color(0, 0, 0));
        
        dashboardContainer.removeAll();
        dashboardContainer.repaint();
        dashboardContainer.revalidate();
        dashboardContainer.add(chartsTab);
        dashboardContainer.repaint();
        dashboardContainer.revalidate();
        
    }//GEN-LAST:event_chartsBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        searchBtn.setBackground(new Color(255, 255, 255));
        
        profileBtn.setBackground(new Color(0, 0, 0));
        chartsBtn.setBackground(new Color(0, 0, 0));
        logoutBtn.setBackground(new Color(0, 0, 0));
        
        dashboardContainer.removeAll();
        dashboardContainer.repaint();
        dashboardContainer.revalidate();
        dashboardContainer.add(searchTab);
        dashboardContainer.repaint();
        dashboardContainer.revalidate();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        logoutBtn.setBackground(new Color(255, 255, 255));
        
        profileBtn.setBackground(new Color(0, 0, 0));
        chartsBtn.setBackground(new Color(0, 0, 0));
        searchBtn.setBackground(new Color(0, 0, 0));
        
        dashboardContainer.removeAll();
        dashboardContainer.repaint();
        dashboardContainer.revalidate();
        dashboardContainer.add(logoutTab);
        dashboardContainer.repaint();
        dashboardContainer.revalidate();
        
        
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void confirmLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmLogoutBtnActionPerformed
        User user = new User();
        this.dispose();
        user.setUserActive(false);
        user.logoutActivity();
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_confirmLogoutBtnActionPerformed

    // Get Project Data from Database
    private void getProjectTable() {
        PreparedStatement st;
        ResultSet rs;
        try {
            String query = "SELECT projectAcronym, projectStatus, proName, proTopics, projectTitle, startDate, endDate, projectURL, projectObjectives FROM project";
            st = DBConnection.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            searchResults.setModel(DbUtils.resultSetToTableModel(rs));
        } 
        catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void findProject(JTable table, JTextField input) {
        // Table Row Data Filter
        TableRowSorter<TableModel> dataSorter = new TableRowSorter<>(table.getModel());
        table.setRowSorter(dataSorter);
        input.getDocument().addDocumentListener(new DocumentListener() {
            
            // Check Character added from User Input
            @Override
            public void insertUpdate(DocumentEvent e) {
                String txt = input.getText();
                
                if(txt.trim().length() == 0) {
                    dataSorter.setRowFilter(null);
                }
                else {
                    dataSorter.setRowFilter(RowFilter.regexFilter("(?i)" + txt));
                }
            }
            
            // Check Character removed from User Input
            @Override
            public void removeUpdate(DocumentEvent e) {
                String txt = input.getText();
                
                if(txt.trim().length() == 0) {
                    dataSorter.setRowFilter(null);
                }
                else {
                    dataSorter.setRowFilter(RowFilter.regexFilter("(?i)" + txt));
                }
            }
            
            // Throw void Exception
            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("");
            }
        });
    }
    
    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnMouseEntered

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        minimizeBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void addDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataActionPerformed
        DataWizard newData = new DataWizard();
        newData.setVisible(true);
        newData.pack();
        newData.setLocationRelativeTo(null);
    }//GEN-LAST:event_addDataActionPerformed

    private void userLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLogActionPerformed
        UserDataLog displayUsers = new UserDataLog();
        displayUsers.setVisible(true);
        displayUsers.pack();
        displayUsers.setLocationRelativeTo(null);
    }//GEN-LAST:event_userLogActionPerformed

    private void chartPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartPreviewActionPerformed
        ChartData chart;
        switch (proChartSelect.getSelectedIndex()) {
            case 0:
            // PROJECT CHART OBJECT - Project Status vs Total Cost Line Chart
            chart = new ChartData("Project Status vs Total Cost Line Chart");
            chart.statusVStcBarChart("Projects Chart", "Project Status", "Total Cost");
            chart.setVisible(true);
            break;
            
            case 1:
            // PROJECT CHART OBJECT - Funding Scheme vs Total Cost Bar Chart
            chart = new ChartData("Funding Scheme vs Total Cost Bar Chart");
            chart.schemeVStcBarChart("Projects Chart", "Funding Scheme", "Total Cost");
            chart.setVisible(true);    
            break; 
            
            case 2:
            // PROJECT CHART OBJECT - Total Cost vs ecMaxContribution Bar Chart
            chart = new ChartData("Total Cost vs ecMaxContributions Bar Chart");
            chart.tcVSecBarChart("Projects Chart", "Total Cost", "Contributions");
            chart.setVisible(true);        
            break;
            
            case 3:
            // PROJECT CHART OBJECT - Total Cost vs ecMaxContribution Bar Chart
            chart = new ChartData("Signed Grants/Participant EU Contribution");
            chart.tcVSecBarChart("Projects Chart", "Name", "Contributions");
            chart.setVisible(true);        
            break;
            
        }
        
    }//GEN-LAST:event_chartPreviewActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addData;
    public javax.swing.JPanel adminControlPanel;
    private javax.swing.JPanel chartDataSelect;
    private javax.swing.JButton chartPreview;
    private javax.swing.JButton chartsBtn;
    private javax.swing.JLabel chartsLbl;
    private javax.swing.JPanel chartsTab;
    private javax.swing.JButton confirmLogoutBtn;
    private javax.swing.JPanel cwContainer;
    private javax.swing.JPanel cwInfoPanel;
    private javax.swing.JPanel dashboardContainer;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lastLogin;
    private javax.swing.JLabel lineSeperator;
    private javax.swing.JLabel lineSeperator1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel logoutLbl;
    private javax.swing.JPanel logoutTab;
    private javax.swing.JLabel logoutWarningLbl;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JPanel navBar;
    public static javax.swing.JComboBox<String> proChartSelect;
    private javax.swing.JButton profileBtn;
    private javax.swing.JPanel profileContainer;
    private javax.swing.JScrollPane profileTab;
    private javax.swing.JButton searchBtn;
    public static javax.swing.JTextField searchInput;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JTable searchResults;
    public javax.swing.JPanel searchTab;
    public javax.swing.JLabel sessionID;
    private javax.swing.JPanel titleBar;
    public javax.swing.JLabel userEmail;
    private javax.swing.JButton userLog;
    public javax.swing.JLabel userName;
    public javax.swing.JLabel userType;
    public javax.swing.JLabel userfName;
    public javax.swing.JLabel userfNameTitle;
    public javax.swing.JLabel userlName;
    // End of variables declaration//GEN-END:variables



}
