/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Color;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.apache.log4j.PropertyConfigurator;

/**
 *
 * @author User
 */
public class DataWizard extends javax.swing.JFrame {

    static boolean maximized = true;
    static boolean loggedIn = true;
    int xMouse;
    int yMouse;
    String filePath;
    Connection conn = null;
    PreparedStatement st;
    ResultSet rs;
    static File selectedFile;
    
    /**
     * Creates new form DataWizard
     */
    public DataWizard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        titleBar = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        wizardStart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectFileBtn = new javax.swing.JButton();
        fileLocation = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dataType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        previewData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("dwFrame"); // NOI18N
        setUndecorated(true);

        titleBar.setBackground(new java.awt.Color(0, 0, 0));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        minimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/minimize.png"))); // NOI18N
        minimizeBtn.setToolTipText("Minimize");
        minimizeBtn.setContentAreaFilled(false);
        minimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        minimizeBtn.setMaximumSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setMinimumSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setOpaque(true);
        minimizeBtn.setPreferredSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/minimizeSelected.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(0, 0, 0));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/exit.png"))); // NOI18N
        exitBtn.setToolTipText("Exit");
        exitBtn.setContentAreaFilled(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn.setMaximumSize(new java.awt.Dimension(64, 64));
        exitBtn.setMinimumSize(new java.awt.Dimension(64, 64));
        exitBtn.setOpaque(true);
        exitBtn.setPreferredSize(new java.awt.Dimension(64, 64));
        exitBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/exitSelected.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        wizardStart.setBackground(new java.awt.Color(255, 255, 255));
        wizardStart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Data to System");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Select Data Type:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Select File:");

        selectFileBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        selectFileBtn.setText("Select Data File");
        selectFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileBtnActionPerformed(evt);
            }
        });

        fileLocation.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        fileLocation.setText(" ");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setText(".xls, .xlsx only");

        dataType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        dataType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Project", "Participant" }));
        dataType.setSelectedItem(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("File Path:");

        previewData.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        previewData.setText("Preview Data");
        previewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wizardStartLayout = new javax.swing.GroupLayout(wizardStart);
        wizardStart.setLayout(wizardStartLayout);
        wizardStartLayout.setHorizontalGroup(
            wizardStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizardStartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wizardStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(wizardStartLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dataType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(wizardStartLayout.createSequentialGroup()
                        .addGroup(wizardStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(wizardStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wizardStartLayout.createSequentialGroup()
                                .addGroup(wizardStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(previewData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(wizardStartLayout.createSequentialGroup()
                                .addComponent(selectFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))))
                .addContainerGap())
        );
        wizardStartLayout.setVerticalGroup(
            wizardStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizardStartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wizardStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wizardStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(selectFileBtn)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wizardStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileLocation)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(previewData)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(wizardStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(wizardStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        minimizeBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_exitBtnMouseEntered

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        if (maximized) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_titleBarMouseDragged

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void selectFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileBtnActionPerformed
        JFileChooser dataImport = new JFileChooser();
        String fp = setFilePath(dataImport).toString();
    }//GEN-LAST:event_selectFileBtnActionPerformed

    private void previewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewDataActionPerformed
        // IF DataType = Project
        if (dataType.getSelectedIndex() == 0) {
            
            // Create new Data Preview Window
            PreviewUpload projectPreview = new PreviewUpload();     
            
            try {
                // Import Excel to JTable
                projectPreview.projectExcel(selectedFile);
                
                // Add User Activity Log Message
                projectPreview();
            } catch (IOException ex) {
                Logger.getLogger(DataWizard.class.getName()).log(Level.SEVERE, null, ex);
            }
            projectPreview.setExtendedState(MAXIMIZED_BOTH);
            projectPreview.setVisible(true);
            projectPreview.pack();
            projectPreview.setLocationRelativeTo(null);
        }
        
        // IF DataType = Participant
        if (dataType.getSelectedIndex() == 1) {
            // Create new Data Preview Window
            PreviewUpload partPreview = new PreviewUpload();
            try {
                // Import Excel to JTable
                partPreview.partExcel(selectedFile);
                
                // Add User Activity Log Message
                partPreview();
            } catch (IOException ex) {
                Logger.getLogger(DataWizard.class.getName()).log(Level.SEVERE, null, ex);
            }
            partPreview.setExtendedState(MAXIMIZED_BOTH);
            partPreview.setVisible(true);
            partPreview.pack();
            partPreview.setLocationRelativeTo(null);
            this.dispose();
        }
        // ELSE - No item selected
        if (dataType.getSelectedItem() == null) {
            // DISPLAY Error Message
            JOptionPane.showMessageDialog(null, "Please Select a DataType to continue", "No Data Type Selected", 2);
        }
    }//GEN-LAST:event_previewDataActionPerformed
    public JLabel setFilePath(JFileChooser fc){
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        int r = fc.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) { 
            selectedFile = fc.getSelectedFile();
            filePath = selectedFile.getAbsolutePath();
            System.out.println("Selected File: " + filePath);
            fileLocation.setText(filePath);
        }
        return fileLocation;
    }
    
    // Custom Method for Logging New Preview Data File for Project Data
    public org.apache.log4j.Logger projectPreview() {
        User user = new User();
        org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(User.class);
        String log4jConfigFile = System.getProperty("user.dir") + File.separator + "log4j.properties";
        PropertyConfigurator.configure(log4jConfigFile);
        if (user.isUserActive() == true) {
            logger.debug(
                "Username: " + user.getUsername() + 
                " - is importing Project Data to System");
        }
        return logger;
    }
    
    // Custom Method for Logging New Preview Data File for Project Data
    public org.apache.log4j.Logger partPreview() {
        User user = new User();
        org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(User.class);
        String log4jConfigFile = System.getProperty("user.dir") + File.separator + "log4j.properties";
        PropertyConfigurator.configure(log4jConfigFile);
        if (user.isUserActive() == true) {
            logger.debug(
                "Username: " + user.getUsername() + 
                " - is importing Participant Data to System");
        }
        return logger;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DataWizard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> dataType;
    private javax.swing.JButton exitBtn;
    public javax.swing.JLabel fileLocation;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JButton previewData;
    private javax.swing.JButton selectFileBtn;
    private javax.swing.JPanel titleBar;
    private javax.swing.JPanel wizardStart;
    // End of variables declaration//GEN-END:variables
}
