/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import static frame.User.newUser;
import java.awt.Color;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Christopher Rees - W1710551
 */
public class Login extends javax.swing.JFrame {  
    
    // Client Variables
    static boolean maximized = true;
    int xMouse;
    int yMouse;
    long count;
    SimpleDateFormat sd = new SimpleDateFormat("YYYY-mm-dd HH:mm:ss");

    
    // landing Class Constructor
    public Login() {
        initComponents();
        
        // Center Align Form on Screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        landingContainer = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        login_username = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        regLbl7 = new javax.swing.JLabel();
        emailLbl1 = new javax.swing.JLabel();
        login_password = new javax.swing.JPasswordField();
        registerPanel = new javax.swing.JPanel();
        regLbl1 = new javax.swing.JLabel();
        regLbl2 = new javax.swing.JLabel();
        regLbl5 = new javax.swing.JLabel();
        regLbl6 = new javax.swing.JLabel();
        emailReg = new javax.swing.JTextField();
        userReg = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        regConfirm = new javax.swing.JButton();
        regLbl8 = new javax.swing.JLabel();
        regLbl9 = new javax.swing.JLabel();
        userPass1 = new javax.swing.JPasswordField();
        userPass2 = new javax.swing.JPasswordField();
        regLbl10 = new javax.swing.JLabel();
        lNameReg = new javax.swing.JTextField();
        regLbl11 = new javax.swing.JLabel();
        fNameReg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(300, 400));
        setName("loginRegister"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(300, 400));

        titleBar.setBackground(new java.awt.Color(0, 0, 0));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        minimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/minimize.png"))); // NOI18N
        minimizeBtn.setToolTipText("Minimize");
        minimizeBtn.setContentAreaFilled(false);
        minimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        minimizeBtn.setMaximumSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setMinimumSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setOpaque(true);
        minimizeBtn.setPreferredSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/minimizeSelected.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(0, 0, 0));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/exit.png"))); // NOI18N
        exitBtn.setToolTipText("Exit");
        exitBtn.setContentAreaFilled(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn.setMaximumSize(new java.awt.Dimension(64, 64));
        exitBtn.setMinimumSize(new java.awt.Dimension(64, 64));
        exitBtn.setOpaque(true);
        exitBtn.setPreferredSize(new java.awt.Dimension(64, 64));
        exitBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/exitSelected.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        landingContainer.setBackground(new java.awt.Color(255, 255, 255));
        landingContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        landingContainer.setMinimumSize(new java.awt.Dimension(300, 400));
        landingContainer.setName(""); // NOI18N
        landingContainer.setPreferredSize(new java.awt.Dimension(300, 400));
        landingContainer.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setPreferredSize(new java.awt.Dimension(300, 400));

        loginBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.setToolTipText("Click to Login");
        loginBtn.setBorder(null);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setFocusable(false);
        loginBtn.setMaximumSize(new java.awt.Dimension(63, 21));
        loginBtn.setMinimumSize(new java.awt.Dimension(63, 21));
        loginBtn.setPreferredSize(new java.awt.Dimension(63, 21));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        login_username.setForeground(new java.awt.Color(153, 153, 153));
        login_username.setMaximumSize(new java.awt.Dimension(7, 20));

        emailLbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        emailLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLbl.setText("Username:");

        regLbl7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        regLbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regLbl7.setText("Horizon Funding 2020");

        emailLbl1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        emailLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLbl1.setText("Password:");

        login_password.setText("password");
        login_password.setMaximumSize(new java.awt.Dimension(7, 20));
        login_password.setPreferredSize(new java.awt.Dimension(7, 20));

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(login_username, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(emailLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(regLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regLbl7)
                .addGap(140, 140, 140)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        landingContainer.add(loginPanel, "card2");

        registerPanel.setBackground(new java.awt.Color(255, 255, 255));

        regLbl1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        regLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regLbl1.setText("Horizon Funding 2020");

        regLbl2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        regLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regLbl2.setText("User Registration");

        regLbl5.setBackground(new java.awt.Color(255, 255, 255));
        regLbl5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        regLbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regLbl5.setText("Email:");
        regLbl5.setOpaque(true);

        regLbl6.setBackground(new java.awt.Color(255, 255, 255));
        regLbl6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        regLbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regLbl6.setText("Username:");
        regLbl6.setOpaque(true);

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        backBtn.setText("BACK");
        backBtn.setToolTipText("Back to Login Screen");
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setMaximumSize(new java.awt.Dimension(70, 25));
        backBtn.setMinimumSize(new java.awt.Dimension(70, 25));
        backBtn.setPreferredSize(new java.awt.Dimension(70, 25));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        regConfirm.setBackground(new java.awt.Color(255, 255, 255));
        regConfirm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        regConfirm.setText("REGISTER");
        regConfirm.setToolTipText("Confirm New Account");
        regConfirm.setBorder(null);
        regConfirm.setBorderPainted(false);
        regConfirm.setMaximumSize(new java.awt.Dimension(55, 25));
        regConfirm.setMinimumSize(new java.awt.Dimension(55, 25));
        regConfirm.setPreferredSize(new java.awt.Dimension(55, 25));
        regConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regConfirmActionPerformed(evt);
            }
        });

        regLbl8.setBackground(new java.awt.Color(255, 255, 255));
        regLbl8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        regLbl8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regLbl8.setText("Password:");
        regLbl8.setOpaque(true);

        regLbl9.setBackground(new java.awt.Color(255, 255, 255));
        regLbl9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        regLbl9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regLbl9.setText("Confirm Password:");
        regLbl9.setOpaque(true);

        userPass1.setText("jPasswordField1");

        userPass2.setText("jPasswordField1");

        regLbl10.setBackground(new java.awt.Color(255, 255, 255));
        regLbl10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        regLbl10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regLbl10.setText("Last Name:");
        regLbl10.setOpaque(true);

        regLbl11.setBackground(new java.awt.Color(255, 255, 255));
        regLbl11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        regLbl11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regLbl11.setText("First Name:");
        regLbl11.setOpaque(true);

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGap(35, 80, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(regLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(regLbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(0, 62, Short.MAX_VALUE)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regLbl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regLbl11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailReg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userReg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(regLbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regLbl2)
                .addGap(31, 31, 31)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regLbl11)
                    .addComponent(fNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regLbl10)
                    .addComponent(lNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regLbl5)
                    .addComponent(emailReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regLbl6)
                    .addComponent(userReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regLbl8)
                    .addComponent(userPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regLbl9)
                    .addComponent(userPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        landingContainer.add(registerPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(landingContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(landingContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 373, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(300, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        minimizeBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_exitBtnMouseEntered

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        if (maximized) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_titleBarMouseDragged

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    // LOGIN BUTTON - CLICK ACTION
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // Get username for user input
        String username = login_username.getText();
        String password = String.valueOf(login_password.getPassword());
        
        // Create "Select" Query to find user in "h2020_user" Table
        String query = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";
        
        PreparedStatement st;
        ResultSet rs;
        
        try {
            st = DBConnection.getConnection().prepareStatement(query);
            
            st.setString(1, username);
            st.setString(2, password);
            rs = st.executeQuery();
            
            // If User exists in User Table: 
            if (rs.next()) {
                
                // GET user details & store in user Object
                User newSession = new User();
                
                newSession.setUserActive(true);
                newSession.setUserID(rs.getInt("userID"));
                newSession.setSessionID();
                newSession.setUserType(rs.getString("user_type"));
                newSession.setfName(rs.getString("first_name"));
                newSession.setlName(rs.getString("last_name"));
                newSession.setEmail(rs.getString("email"));
                newSession.setUsername(rs.getString("username"));
                newSession.setProfileImg("profile_image");
                newSession.setLastLogin(rs.getTimestamp("last_login"));
                
                // Log User Activity
                newSession.loginActivity();
                // Display Dashboard
                Dashboard dashboard = new Dashboard();
                dashboard.userfNameTitle.setText(newSession.getfName() + " " + newSession.getlName());
                dashboard.userType.setText(newSession.getUserType());
                dashboard.userName.setText(newSession.getUsername());
                dashboard.userfName.setText(newSession.getfName());
                dashboard.userlName.setText(newSession.getlName());
                dashboard.userEmail.setText(newSession.getEmail());
                dashboard.sessionID.setText(String.valueOf(newSession.getSessionID()));
                dashboard.lastLogin.setText(newSession.getLastLogin().toString());
                
                if (newSession.userType.equalsIgnoreCase("User")) {
                    dashboard.adminControlPanel.setVisible(false);
                    dashboard.setVisible(true);
                    dashboard.pack();
                    dashboard.setLocationRelativeTo(null);
                }
                else {
                    dashboard.adminControlPanel.setVisible(true);
                    dashboard.setVisible(true);
                    dashboard.pack();
                    dashboard.setLocationRelativeTo(null);
                }
                
                // Close Login Form
                this.dispose();
                // Display console message
                System.out.println("User: " + newSession.getUsername() + " - Role: " + newSession.getUserType() + " has logged in Successfully.");
            }
            
            // If User does not exist in User Table:
            else {
                // Error Message Pop-Up
                JOptionPane.showMessageDialog(null, "Incorrect details, create new account", "Login Error", 2);
                
                // Hide Login Form
                landingContainer.removeAll();
                landingContainer.repaint();
                landingContainer.revalidate();
                
                // Display Register Form
                landingContainer.add(registerPanel);
                landingContainer.repaint();
                landingContainer.revalidate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // Hide Register Form
        landingContainer.removeAll();
        landingContainer.repaint();
        landingContainer.revalidate();
        
        // Display Login Form
        landingContainer.add(loginPanel);
        landingContainer.repaint();
        landingContainer.revalidate();
    }//GEN-LAST:event_backBtnActionPerformed

    private void regConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regConfirmActionPerformed
        String regfName = fNameReg.getText();
        String reglName = lNameReg.getText();
        String regUser = userReg.getText();
        String regEmail = emailReg.getText();
        String regPass = String.valueOf(userPass1.getPassword());
        String userType = "User";
        Timestamp dateTime = new Timestamp(System.currentTimeMillis());
        
        if (verify()) {
            if (!checkUser(regEmail, regUser)) {
                int userID = newUser(regfName, reglName, regEmail, regPass, regUser, dateTime, userType);
                User newSession = new User(userID, regfName, reglName, regUser, regEmail, userType);
                System.out.println("New User Added - User ID: " + userID);
                System.out.println("New Session - User ID: " + userID + " - Session ID: " + newSession.getSessionID());
                
                // Display Dashboard
                Dashboard dashboard = new Dashboard();
                dashboard.userfNameTitle.setText(newSession.getfName() + " " + newSession.getlName());
                dashboard.sessionID.setText(newSession.getSessionID());
                dashboard.userType.setText(newSession.getUserType());
                dashboard.userName.setText(newSession.getUsername());
                dashboard.userfName.setText(newSession.getfName());
                dashboard.userlName.setText(newSession.getlName());
                dashboard.userEmail.setText(newSession.getEmail());
                dashboard.lastLogin.setText(dateTime.toString());
                
                dashboard.setVisible(true);
                dashboard.pack();
                dashboard.setLocationRelativeTo(null);
                
                // Close Login Form
                this.dispose();
                newSession.registerActivity();
                System.out.println("User: " + regUser + " has logged in Successfully.");
            }
        }  
    }//GEN-LAST:event_regConfirmActionPerformed

    // Verify User Input
    public boolean verify() {
        String fName = fNameReg.getText();
        String lName = lNameReg.getText();
        String uName = userReg.getText();
        String pass = String.valueOf(userPass1.getPassword());
        String confirmPass = String.valueOf(userPass2.getPassword());
        
        // Check if any fields are empty
        if (fName.trim().equals("") || lName.trim().equals("") || uName.trim().equals("") || pass.trim().equals("") || confirmPass.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "One or more fields are empty", "Empty Fields", 2);
            return false;
        }
        
        // Check passwords match
        else if(!pass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(null, "Passwords Do Not Match", "Confirm Password", 2);
            return false;
        }
 
        // All fields entered correctly
        else {
            return true;
        }  
    }
    
    // Function to check if Email entered already exists in Database
    public boolean checkUser(String email, String userName) {
        PreparedStatement st;
        ResultSet rs;
        boolean userExists = false;
        
        String query = "SELECT * FROM `users` WHERE `email` = ? OR `username` = ?";
        
        try {
            st = DBConnection.getConnection().prepareStatement(query);
            st.setString(1, email);
            st.setString(2, userName);
            rs = st.executeQuery();
            
            if (rs.next()) {
                userExists = true;
                JOptionPane.showMessageDialog(null, "This email address, username is already registered, please try logging in or resetting your password", "Email Failed", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userExists;
    }
    
    /*
    * Add new User to User Table & return user ID
    * @param fName
    * @param lName
    * @param uName
    * @param email
    * @param pass
    * @return
    */
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Landing Frame Components */
        //<editor-fold defaultstate="collapsed" desc=" Landing Frame Components ">
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel emailLbl1;
    public javax.swing.JTextField emailReg;
    private javax.swing.JButton exitBtn;
    public javax.swing.JTextField fNameReg;
    public javax.swing.JTextField lNameReg;
    public static javax.swing.JPanel landingContainer;
    private static javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField login_password;
    public static javax.swing.JTextField login_username;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JButton regConfirm;
    private javax.swing.JLabel regLbl1;
    private javax.swing.JLabel regLbl10;
    private javax.swing.JLabel regLbl11;
    private javax.swing.JLabel regLbl2;
    private javax.swing.JLabel regLbl5;
    private javax.swing.JLabel regLbl6;
    private javax.swing.JLabel regLbl7;
    private javax.swing.JLabel regLbl8;
    private javax.swing.JLabel regLbl9;
    public static javax.swing.JPanel registerPanel;
    private javax.swing.JPanel titleBar;
    private javax.swing.JPasswordField userPass1;
    private javax.swing.JPasswordField userPass2;
    public static javax.swing.JTextField userReg;
    // End of variables declaration//GEN-END:variables

}
