/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Color;
import java.awt.Frame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class UserDataLog extends javax.swing.JFrame {

    static boolean maximized = true;
    static boolean loggedIn = true;
    int xMouse;
    int yMouse;
    PreparedStatement st;
    ResultSet rs;
    
    /**
     * Creates new form PreviewProjectData
     */
    public UserDataLog() {
        initComponents();
        getUserTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        minimizeBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        dataContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        logView = new javax.swing.JTextArea();
        userLogTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titleBar.setBackground(new java.awt.Color(0, 0, 0));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        minimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/minimize.png"))); // NOI18N
        minimizeBtn.setToolTipText("Minimize");
        minimizeBtn.setContentAreaFilled(false);
        minimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        minimizeBtn.setMaximumSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setMinimumSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setOpaque(true);
        minimizeBtn.setPreferredSize(new java.awt.Dimension(64, 64));
        minimizeBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/minimizeSelected.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(0, 0, 0));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/exit.png"))); // NOI18N
        exitBtn.setToolTipText("Exit");
        exitBtn.setContentAreaFilled(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn.setMaximumSize(new java.awt.Dimension(64, 64));
        exitBtn.setMinimumSize(new java.awt.Dimension(64, 64));
        exitBtn.setOpaque(true);
        exitBtn.setPreferredSize(new java.awt.Dimension(64, 64));
        exitBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/userBar/exitSelected.png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(845, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataContainer.setBackground(new java.awt.Color(255, 255, 255));
        dataContainer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);
        // Prevent User Details from being changed by Admin User
        userTable.setDefaultEditor(Object.class, null);

        logView.setColumns(20);
        logView.setRows(5);
        jScrollPane2.setViewportView(logView);

        userLogTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        userLogTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userLogTitle.setText("User Log: ");

        javax.swing.GroupLayout dataContainerLayout = new javax.swing.GroupLayout(dataContainer);
        dataContainer.setLayout(dataContainerLayout);
        dataContainerLayout.setHorizontalGroup(
            dataContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
            .addComponent(userLogTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dataContainerLayout.setVerticalGroup(
            dataContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataContainerLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLogTitle)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dataContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dataContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        minimizeBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_exitBtnMouseEntered

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        if (maximized) {
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_titleBarMouseDragged

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        try { 
            int row = userTable.getSelectedRow();
            String tableSelect = userTable.getModel().getValueAt(row, 0).toString();
            String query = "SELECT * FROM users WHERE userID='"+tableSelect+"' ";
            st = DBConnection.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            
            while (rs.next()) {
                String fName = rs.getString("first_name");
                String lName = rs.getString("last_name");
                String uName = rs.getString("username");
                
                userLogTitle.setText("User Log: " + fName + " " + lName + " - Username: " + uName);
                logView.setText("");
                
                String query2 = "SELECT * FROM user_log WHERE message LIKE ?";
                st = DBConnection.getConnection().prepareStatement(query2, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                st.setString(1, "%" + uName + "%");
                ResultSet rs2 = st.executeQuery();
                int count = 0;
                if (rs2.last()) {
                    count = rs.getRow();
                    rs2.beforeFirst();
                } 
                while (rs2.next()) {
                    int logID = rs2.getInt("logID");
                    String messageType = rs2.getString("messageType");
                    Timestamp dateTime = rs2.getTimestamp("dateTime");
                    String handler = rs2.getString("handler");
                    String className = rs2.getString("class");
                    String message = rs2.getString("message");
                    for (int i = 0; i < count; i++) {
                        logView.append(logID + " - " + messageType + " - " + dateTime + " - " + handler + " - " + className + " - " + message + "\n");
                    } 
                } 
            }        
        }
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    }//GEN-LAST:event_userTableMouseClicked

    private void getUserTable() {
        try {
            String query = "SELECT * FROM users";
            st = DBConnection.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            userTable.setModel(DbUtils.resultSetToTableModel(rs));
        } 
        catch (SQLException ex) {
            Logger.getLogger(UserDataLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDataLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserDataLog().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataContainer;
    private javax.swing.JButton exitBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea logView;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel userLogTitle;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
